[supervisord]
nodaemon=true
user=root

[program:api]
command=uvicorn openf1.main:app --host 0.0.0.0 --port 10000
directory=/app/src
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:ingest_realtime]
command=python -m openf1.services.ingestor_livetiming.main
directory=/app/src
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:ingest_historical]
command=python -m openf1.services.f1_scraping.main
directory=/app/src
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
